POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtlbiIsImlkIjoiNjk1NGEyNTIxZTg4ZGFiMTBlNTJlMjZlIiwiaWF0IjoxNzY3MzMzMTk2fQ.-imSnLcVi8xpUqx1ZK5IuB-_VN_PRPjtpF1fG-xOx1Y

{
    "title": "JK",
    "author": "JHIK J",
    "url": "www.jklfjdkf.com",
    "likes": 20
}

###
POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtlbiIsImlkIjoiNjk1NGEyNTIxZTg4ZGFiMTBlNTJlMjZlIiwiaWF0IjoxNzY3MzMzMTk2fQ.-imSnLcVi8xpUqx1ZK5IuB-_VN_PRPjtpF1fG-xOx1Y

{
    "title": "Cool Blog",
    "author": "Collin Cold",
    "url": "www.coolblog.com",
    "likes": 23
}

###
POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtlbiIsImlkIjoiNjk1NGEyNTIxZTg4ZGFiMTBlNTJlMjZlIiwiaWF0IjoxNzY3MTU0MjcxfQ.9b7lhh_84loPvMuZM0Mu7zXDzHGq_UMUBBCrZiouSxc

{
    "title": "Frisey",
    "author": "Freight",
    "url": "www.frisey.com",
    "likes": 23
}
###

DELETE http://localhost:3003/api/blogs/6954a2bd5f64cc12a53a922d
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtlbiIsImlkIjoiNjk1NGEyNTIxZTg4ZGFiMTBlNTJlMjZlIiwiaWF0IjoxNzY3MTU0MjcxfQ.9b7lhh_84loPvMuZM0Mu7zXDzHGq_UMUBBCrZiouSxc

###
GET http://localhost:3003/api/blogs