POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtlbiIsImlkIjoiNjk1MzViZDk0YWFlYzYzOTg1ZWE0YjdiIiwiaWF0IjoxNzY3MDcwNzMwfQ.CzVf_jFmspxs-K7U436g_5p1MK9b5kH3t1xTYBzFOt8

{
    "title": "JK",
    "author": "JHIK J",
    "url": "www.jklfjdkf.com",
    "likes": 20
}

###
POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtlbiIsImlkIjoiNjk1MzViZDk0YWFlYzYzOTg1ZWE0YjdiIiwiaWF0IjoxNzY3MDcwNzMwfQ.CzVf_jFmspxs-K7U436g_5p1MK9b5kH3t1xTYBzFOt8

{
    "title": "Cool Blog",
    "author": "Collin Cold",
    "url": "www.coolblog.com",
    "likes": 23
}

###
POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlbnJ5IiwiaWQiOiI2OTUzNWJlMTRhYWVjNjM5ODVlYTRiN2QiLCJpYXQiOjE3NjcwNzA4MTB9.x8XpLW8cvknbX6BG_pRtMyzOOtkmsLDUUe1mccYvf1M

{
    "title": "Frisey",
    "author": "Freight",
    "url": "www.frisey.com",
    "likes": 23
}

###
GET http://localhost:3003/api/blogs