POST http://localhost:3003/api/users
content-type: application/json

{
    "username": "ken",
    "name": "ji",
    "password": "nek"
}

###
POST http://localhost:3003/api/users
content-type: application/json

{
    "username": "ben",
    "name": "hiimhenry",
    "password": "hen"
}

###
GET http://localhost:3003/api/users